# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cineFast', '0002_auto_20160323_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('caminho_foto', models.CharField(max_length=100, null=True, verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Diretor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('caminho_foto', models.CharField(max_length=100, null=True, verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='filme',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filme',
            name='caminho_trailer',
            field=models.CharField(default=1, max_length=100, verbose_name='Trailer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='caminho_imagem',
            field=models.CharField(max_length=100, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='data_lancamento',
            field=models.DateField(blank=True, verbose_name='Data de Lançamento'),
        ),
    ]
