# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineFast', '0003_auto_20160323_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='caminho_imagem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='caminho_trailer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trailer'),
        ),
    ]
