# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cineFast', '0004_auto_20160323_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='elenco',
            name='atores',
            field=models.ManyToManyField(to='cineFast.Ator'),
        ),
        migrations.AddField(
            model_name='elenco',
            name='diretores',
            field=models.ManyToManyField(to='cineFast.Diretor'),
        ),
        migrations.AddField(
            model_name='filme',
            name='elenco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cineFast.Elenco'),
        ),
    ]
