# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cineFast', '0006_filme_em_cartaz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('data', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cineFast.Filme')),
            ],
        ),
    ]
