# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineFast', '0007_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
