# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-08 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineFast', '0008_auto_20160329_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='diretor',
            name='file',
            field=models.FileField(null=True, upload_to='C://cineFast/img'),
        ),
    ]
