# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineFast', '0019_auto_20160510_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diretor',
            name='foto',
            field=models.ImageField(null=True, upload_to='http://127.0.0.1/Cine-Fast/cine_fast/src/templates/diretor/'),
        ),
    ]
